name: MSYS2

on: 
  workflow_dispatch

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    strategy:
      matrix:
        sys:
          - mingw64
          - mingw32
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git 
      - name: CI-Build
        run: |
          echo 'Running in MSYS2!'
          uname -a 
          ./ci-build.sh
