name: MSYS2

on: 
  workflow_dispatch

jobs:
  build-msys2:
    runs-on: windows-latest
    strategy:
      matrix:
        sys:
          - mingw64
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git unzip bzip2 base-devel mingw-w64-x86_64-toolchain mingw-w64-x86_64-make mingw-w64-x86_64-libtool mingw-w64-x86_64-pkg-config mingw-w64-x86_64-pkgconf mingw-w64-x86_64-autotools mingw-w64-x86_64-texinfo mingw-w64-x86_64-libusb mingw-w64-x86_64-capstone mingw-w64-x86_64-hidapi mingw-w64-x86_64-arm-none-eabi-gcc mingw-w64-x86_64-libftdi  
      - name: Build
        run: |
          echo 'Running in MSYS2!'
          uname -a 
          gcc -v
          git clone --depth=1 --recurse-submodules --branch v0.12.0 https://github.com/openocd-org/openocd.git
          cd openocd
          ./bootstrap
          export CFLAGS="$CFLAGS -Wno-error"
          mkdir -pv build
          cd build
          ../configure --program-prefix=kuo --enable-static
          make
          ls -rR ./
          
          
