name: MSYS2

on: 
  workflow_dispatch

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    strategy:
      matrix:
        sys:
          - mingw64
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git make libtool pkg-config pkgconfig autotools texinfo libusb 
      - name: Build
        run: |
          echo 'Running in MSYS2!'
          uname -a 
          git clone --depth=1 --recurse-submodules --branch v0.12.0 https://github.com/openocd-org/openocd.git
          cd openocd
          ./bootstrap
          export CFLAGS="$CFLAGS -Wno-error"
          mkdir build
          cd build
          ../configure
          
          
